# Generated by Django 4.0.3 on 2022-04-26 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAccount', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequestFormQuesitons',
            fields=[
                ('Question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('HeartDisease', models.TextField(blank=True, null=True)),
                ('Kidney_Lung_Bloodpressure_Diabetes_Epilepsy', models.TextField(blank=True, null=True)),
                ('Liverproblems', models.TextField(blank=True, null=True)),
                ('STD', models.TextField(blank=True, null=True)),
                ('Tattoo_Ear_skin_pierced_lastmonth', models.TextField(blank=True, null=True)),
                ('Slpet_Unsafely_OtherThanPartner', models.TextField(blank=True, null=True)),
                ('SeriousSkinRepair', models.TextField(blank=True, null=True)),
                ('Preagnant', models.TextField(blank=True, null=True)),
                ('Abortion', models.TextField(blank=True, null=True)),
                ('BreastFeeding', models.TextField(blank=True, null=True)),
                ('BloodHealthfulnessInfo', models.TextField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'DonationRequestFormQuesitons',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Donor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Donorname', models.CharField(blank=True, max_length=20, null=True)),
                ('DateOfBirth', models.DateTimeField(blank=True, max_length=6, null=True)),
                ('Bloodgroup', models.CharField(blank=True, choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Age', models.IntegerField()),
                ('Nationality', models.CharField(blank=True, max_length=10, null=True)),
                ('Height', models.CharField(blank=True, max_length=10, null=True)),
                ('Weight', models.CharField(blank=True, max_length=10, null=True)),
                ('BMS', models.FloatField(blank=True, max_length=10, null=True)),
                ('BloodPressure', models.CharField(blank=True, max_length=10, null=True)),
                ('ProfilePic', models.FileField(blank=True, default='profilepic/defaultprofile.jpeg', null=True, upload_to='profilepic/')),
                ('Account_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Address_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.address')),
            ],
            options={
                'db_table': 'Donor',
            },
        ),
        migrations.CreateModel(
            name='DonationRequestFormResult',
            fields=[
                ('Result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('HeartDisease', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Kidney_Lung_Bloodpressure_Diabetes_Epilepsy', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Liverproblems', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('STD', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Tattoo_Ear_skin_pierced_lastmonth', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Slpet_Unsafely_OtherThanPartner', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('SeriousSkinRepair', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Preagnant', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('Abortion', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('BreastFeeding', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('BloodHealthfulnessInfo', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=10, null=True)),
                ('Status', models.CharField(blank=True, default='in progress', max_length=11, null=True)),
                ('Request_time', models.TimeField(auto_now_add=True, null=True)),
                ('Request_Date', models.DateField(auto_now_add=True, null=True)),
                ('Donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.donor')),
            ],
            options={
                'db_table': 'DonationRequestFormResult',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('App_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Time', models.TimeField(default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, default='in progress', max_length=12, null=True)),
                ('Donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.donor')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
