# Generated by Django 4.0.3 on 2022-05-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_alter_donor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Gender',
            field=models.CharField(blank=True, choices=[(None, 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
