# Generated by Django 4.0.3 on 2022-05-04 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_alter_donor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='BMS',
            field=models.FloatField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
