# Generated by Django 4.0.3 on 2022-06-05 19:15

import Donor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0004_alter_donor_age_alter_donor_bms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='BMS',
            field=models.FloatField(blank=True, max_length=10, null=True, validators=[Donor.models.validate_interval]),
        ),
    ]
