# Generated by Django 4.0.3 on 2022-06-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_alter_donor_bms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequestformquesitons',
            name='Type',
        ),
    ]
