# Generated by Django 4.0.3 on 2024-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_remove_donationrequestformquesitons_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Bloodgroup',
            field=models.CharField(choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Gender',
            field=models.CharField(choices=[(None, 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
