# Generated by Django 4.0.3 on 2024-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0007_alter_donor_bloodgroup_alter_donor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='BMS',
        ),
        migrations.AlterField(
            model_name='donor',
            name='DateOfBirth',
            field=models.DateTimeField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
