# Generated by Django 4.0.3 on 2024-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0008_remove_donor_age_remove_donor_bms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Donorname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
