# Generated by Django 4.0.3 on 2026-01-13 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0009_alter_donor_donorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequestQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_field_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_gender_specific', models.BooleanField(default=False)),
                ('gender_required', models.CharField(blank=True, choices=[(None, 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'DonationRequestQuestion',
            },
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Abortion',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='BloodHealthfulnessInfo',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='BreastFeeding',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='HeartDisease',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Kidney_Lung_Bloodpressure_Diabetes_Epilepsy',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Liverproblems',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Preagnant',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='STD',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='SeriousSkinRepair',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Slpet_Unsafely_OtherThanPartner',
        ),
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='Tattoo_Ear_skin_pierced_lastmonth',
        ),
        migrations.CreateModel(
            name='DonationRequestAnswer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=3, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.donationrequestquestion')),
                ('request_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Donor.donationrequestformresult')),
            ],
            options={
                'db_table': 'DonationRequestAnswer',
            },
        ),
    ]
