# Generated by Django 4.0.3 on 2026-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0010_donationrequestquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestanswer',
            name='answer',
            field=models.CharField(blank=True, choices=[(None, 'Answer'), ('yes', 'yes'), ('no', 'no')], max_length=20, null=True),
        ),
    ]
