# Generated by Django 4.0.3 on 2022-04-07 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor', '0015_remove_donationrequestformresult_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequestformresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.AddField(
            model_name='donationrequestformresult',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Donor.donor'),
        ),
        migrations.AddField(
            model_name='donationrequestformresult',
            name='Status',
            field=models.CharField(blank=True, default='in progress', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='Account_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Donor.donor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='in progress', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Donor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
