# Generated by Django 4.0.3 on 2022-04-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0016_remove_donationrequestformresult_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestformresult',
            name='Request_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
