# Generated by Django 4.0.3 on 2022-04-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_alter_account_first_name'),
        ('Donor', '0018_alter_donor_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Address_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.address'),
        ),
    ]
