# Generated by Django 4.0.3 on 2022-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0020_alter_donor_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Bloodgroup',
            field=models.CharField(blank=True, choices=[(None, 'select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB-')], max_length=10, null=True),
        ),
    ]
