# Generated by Django 4.0.3 on 2022-04-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor', '0022_alter_donor_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Account_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
