# Generated by Django 4.0.3 on 2022-04-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0024_alter_appointment_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Donor.donor'),
        ),
    ]
