# Generated by Django 4.0.3 on 2022-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0028_alter_donor_bloodgroup_alter_donor_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestformresult',
            name='Request_Date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Request_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
