# Generated by Django 4.0.3 on 2022-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0029_donationrequestformresult_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestformresult',
            name='Request_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
