# Generated by Django 4.0.3 on 2022-04-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0030_alter_donationrequestformresult_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='ProfilePic',
            field=models.FileField(blank=True, default='profilepic/defaultprofile.jpeg', null=True, upload_to='profilepic/'),
        ),
    ]
