# Generated by Django 4.0.3 on 2022-04-24 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0031_alter_donor_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='DateTime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
