# Generated by Django 4.0.3 on 2022-04-24 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0032_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='DateTime',
            new_name='Date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
