# Generated by Django 4.0.3 on 2022-04-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0017_donationrequestformresult_request_time'),
        ('LabTechnician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fininshedappointment',
            name='Appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.appointment'),
        ),
    ]
