# Generated by Django 4.0.3 on 2022-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Phone',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
