# Generated by Django 4.0.3 on 2022-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_alter_account_email_alter_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
