# Generated by Django 4.0.3 on 2022-05-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0005_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Role',
            field=models.CharField(blank=True, choices=[(None, 'SelectRole'), ('BBManager', 'BBManager'), ('Nurse', 'Nurse'), ('LabTechnician', 'LabTechnician'), ('HospitalRepresentative', 'HospitalRepresentative'), ('Donor', 'Donor')], max_length=25, null=True),
        ),
    ]
