# Generated by Django 4.0.3 on 2024-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0006_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
