# Generated by Django 4.0.3 on 2022-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_alter_account_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Role',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
