# Generated by Django 4.0.3 on 2022-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0008_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='ProfilePic',
            field=models.FileField(blank=True, default='profilepic/defaultprofile.jpeg', null=True, upload_to='profilepic/'),
        ),
    ]
