# Generated by Django 4.0.3 on 2022-05-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='CampPic',
            field=models.FileField(blank=True, default='camps/defaultcamp.png', null=True, upload_to='camps/'),
        ),
    ]
