# Generated by Django 4.0.3 on 2022-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_camp_camppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventName',
            field=models.CharField(max_length=20),
        ),
    ]
