# Generated by Django 4.0.3 on 2022-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_eventname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventTime',
        ),
        migrations.AddField(
            model_name='event',
            name='EventDescription',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
