# Generated by Django 4.0.3 on 2024-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_remove_event_eventtime_event_eventdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDate',
            field=models.DateField(max_length=20),
        ),
    ]
