# Generated by Django 4.0.3 on 2024-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_alter_event_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='CampsKebele',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='CampsName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='camp',
            name='CampsWoreda',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventDescription',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventType',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
