# Generated by Django 4.0.3 on 2022-04-12 09:40

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_auto_20220331_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='CampsPlace',
        ),
        migrations.AddField(
            model_name='camp',
            name='Address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='Geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
