# Generated by Django 4.0.3 on 2026-01-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_alter_camp_campskebele_alter_camp_campsname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='CampsKebele',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='CampsWoreda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
