# Generated by Django 4.0.3 on 2026-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_alter_camp_campskebele_alter_camp_campsworeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='CampsName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camp',
            name='CampsWoreda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
