# Generated by Django 4.0.3 on 2022-04-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_place_remove_camp_address_remove_camp_geolocation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
