# Generated by Django 4.0.3 on 2026-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_alter_camp_campsname_alter_camp_campsworeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventPlace',
            field=models.CharField(max_length=1000),
        ),
    ]
