# Generated by Django 4.0.3 on 2026-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_alter_event_eventdescription_alter_event_eventname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventMap',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
