# Generated by Django 4.0.3 on 2026-02-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_event_eventmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Place',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='Location',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
