# Generated by Django 4.0.3 on 2022-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_alter_event_eventdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='location',
        ),
        migrations.AddField(
            model_name='camp',
            name='Location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
