# Generated by Django 4.0.3 on 2022-04-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_remove_camp_location_camp_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='Location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
