# Generated by Django 4.0.3 on 2022-04-26 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_id', models.UUIDField(blank=True, null=True)),
                ('Donor_id', models.UUIDField(blank=True, null=True)),
                ('BloodGroup', models.CharField(choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('PackNo', models.CharField(max_length=20)),
                ('RegDate', models.DateField(max_length=10)),
                ('ExpDate', models.DateField(max_length=10)),
                ('QuantityOfBlood', models.CharField(max_length=4)),
                ('Action', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'BloodHistory',
            },
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('Blood_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('BloodGroup', models.CharField(choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('PackNo', models.CharField(max_length=20)),
                ('RegDate', models.DateField(auto_now_add=True)),
                ('ExpDate', models.DateField(max_length=10)),
                ('QuantityOfBlood', models.CharField(max_length=4)),
                ('Donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.donor')),
            ],
            options={
                'db_table': 'Blood',
            },
        ),
    ]
