# Generated by Django 4.0.3 on 2022-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0002_blood_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='BloodGroup',
            field=models.CharField(choices=[(None, 'type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB-')], max_length=20),
        ),
    ]
