# Generated by Django 4.0.3 on 2026-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0002_alter_blood_quantityofblood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='QuantityOfBlood',
            field=models.FloatField(),
        ),
    ]
