# Generated by Django 4.0.3 on 2026-02-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0003_alter_blood_quantityofblood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodhistory',
            name='BloodGroup',
        ),
        migrations.RemoveField(
            model_name='bloodhistory',
            name='Donor_id',
        ),
        migrations.RemoveField(
            model_name='bloodhistory',
            name='ExpDate',
        ),
        migrations.RemoveField(
            model_name='bloodhistory',
            name='PackNo',
        ),
        migrations.RemoveField(
            model_name='bloodhistory',
            name='QuantityOfBlood',
        ),
        migrations.RemoveField(
            model_name='bloodhistory',
            name='RegDate',
        ),
        migrations.AlterField(
            model_name='bloodhistory',
            name='Blood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blood.blood'),
        ),
    ]
