# Generated by Django 4.0.3 on 2022-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0004_alter_blood_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='BloodGroup',
            field=models.CharField(choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20),
        ),
    ]
