# Generated by Django 4.0.3 on 2022-04-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0022_alter_donor_account_id'),
        ('Blood', '0005_alter_blood_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Donor.donor'),
        ),
    ]
