# Generated by Django 4.0.3 on 2022-04-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0027_alter_donationrequestformresult_donor_id'),
        ('Blood', '0006_alter_blood_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.donor'),
        ),
    ]
