# Generated by Django 4.0.3 on 2022-04-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0028_alter_donor_bloodgroup_alter_donor_profilepic'),
        ('Blood', '0007_alter_blood_donor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloodGroup', models.CharField(choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('PackNo', models.CharField(max_length=20)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('ExpDate', models.DateTimeField(max_length=10)),
                ('QuantityOfBlood', models.CharField(max_length=4)),
                ('Action', models.CharField(blank=True, max_length=20, null=True)),
                ('Blood_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blood.blood')),
                ('Donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Donor.donor')),
            ],
        ),
    ]
