# Generated by Django 4.0.3 on 2022-04-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0008_bloodhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodhistory',
            name='RegDate',
            field=models.DateTimeField(max_length=10),
        ),
    ]
