# Generated by Django 4.0.3 on 2022-04-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0028_alter_donor_bloodgroup_alter_donor_profilepic'),
        ('Blood', '0009_alter_bloodhistory_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodhistory',
            name='Blood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blood.blood'),
        ),
        migrations.AlterField(
            model_name='bloodhistory',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Donor.donor'),
        ),
    ]
