# Generated by Django 4.0.3 on 2022-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0014_alter_blood_expdate_alter_blood_regdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='ExpDate',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blood',
            name='RegDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloodhistory',
            name='ExpDate',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodhistory',
            name='RegDate',
            field=models.DateField(max_length=10),
        ),
    ]
