# Generated by Django 4.0.3 on 2022-04-26 11:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentChoice',
            fields=[
                ('Appchoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Time', models.TimeField(default=datetime.datetime.now)),
                ('NumberofDonors', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'AppointmentChoice',
            },
        ),
    ]
