# Generated by Django 4.0.3 on 2024-04-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentChoice',
        ),
    ]
