# Generated by Django 4.0.3 on 2022-04-23 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentchoice',
            name='id',
        ),
        migrations.AddField(
            model_name='appointmentchoice',
            name='Appchoice_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
