# Generated by Django 4.0.3 on 2022-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0002_remove_appointmentchoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentchoice',
            name='NumberofDonors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
