# Generated by Django 4.0.3 on 2022-04-24 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0003_appointmentchoice_numberofdonors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentchoice',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='appointmentchoice',
            name='Time',
        ),
        migrations.AddField(
            model_name='appointmentchoice',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
