# Generated by Django 4.0.3 on 2022-04-24 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0004_remove_appointmentchoice_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentchoice',
            name='DateTime',
        ),
        migrations.AddField(
            model_name='appointmentchoice',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointmentchoice',
            name='Time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
