# Generated by Django 4.0.3 on 2022-04-26 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blood', '0001_initial'),
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSentBloods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Req_Id', models.UUIDField(blank=True, null=True)),
                ('Blood_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HospitalSentBloods',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('HospitalName', models.CharField(blank=True, max_length=20, null=True)),
                ('BranchNo', models.CharField(max_length=10)),
                ('HospitalRepresentative', models.CharField(max_length=10)),
                ('ProfilePic', models.FileField(blank=True, default='profilepic/defaultprofile.jpeg.', null=True, upload_to='profilepic/')),
                ('Address_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.address')),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('Blood_Req_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Blood_Group', models.CharField(blank=True, choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('Request_Date', models.DateField(auto_now_add=True, null=True)),
                ('Request_Time', models.TimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(blank=True, default='in progress', max_length=12, null=True)),
                ('Blood_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blood.blood')),
                ('Hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.hospital')),
            ],
            options={
                'db_table': 'BloodRequest',
            },
        ),
    ]
