# Generated by Django 4.0.3 on 2022-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_hospital_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='HospitalName',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
