# Generated by Django 4.0.3 on 2022-04-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_alter_account_first_name'),
        ('Hospital', '0002_bloodrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='City',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Kebele',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='PhoneNo',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Woreda',
        ),
        migrations.AddField(
            model_name='hospital',
            name='Address_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.address'),
        ),
    ]
