# Generated by Django 4.0.3 on 2022-04-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_hospital_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Account_id',
        ),
        migrations.AddField(
            model_name='hospital',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
