# Generated by Django 4.0.3 on 2026-02-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_remove_hospital_username_hospital_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='HospitalName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='HospitalRepresentative',
            field=models.CharField(max_length=100),
        ),
    ]
