# Generated by Django 4.0.3 on 2022-04-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_remove_hospital_account_id_hospital_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='Conatact_NO',
        ),
    ]
