# Generated by Django 4.0.3 on 2022-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_remove_bloodrequest_conatact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='Request_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='Status',
            field=models.CharField(blank=True, default='in progress', max_length=12, null=True),
        ),
    ]
