# Generated by Django 4.0.3 on 2022-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_alter_bloodrequest_blood_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='Blood_Group',
            field=models.CharField(blank=True, choices=[(None, 'type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB-')], max_length=10, null=True),
        ),
    ]
