# Generated by Django 4.0.3 on 2022-04-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_alter_bloodrequest_hospital_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='Hospital_id',
        ),
    ]
