# Generated by Django 4.0.3 on 2022-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_bloodrequest_hospital_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='Blood_Group',
            field=models.CharField(blank=True, choices=[(None, 'Select type'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True),
        ),
    ]
