# Generated by Django 4.0.3 on 2022-04-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0007_alter_blood_donor_id'),
        ('Hospital', '0014_alter_bloodrequest_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='Blood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blood.blood'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='Hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.hospital'),
        ),
    ]
