# Generated by Django 4.0.3 on 2022-04-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0009_alter_bloodhistory_regdate'),
        ('Hospital', '0016_hospital_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSentBloods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Req_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.bloodrequest')),
                ('Blood_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blood.blood')),
            ],
        ),
    ]
