# Generated by Django 4.0.3 on 2022-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0020_alter_hospitalsentbloods_blood_req_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='Request_Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='Request_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
